name: Add team member
description: Add your details to the team page on the website
title: '[Team member]: '
labels: ['team', 'enhancement']
assignees:
  - muffato
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add your details to the ToL website!
  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: Priyanka Surana
    validations:
      required: true
  - type: dropdown
    id: team
    attributes:
      label: Team
      options:
        - Informatics Infrastructure (ToL–IT)
        - Platforms (ToLP)
        - Assembly (ToLA)
        - Curation (GRIT)
        - Other
    validations:
      required: true
  - type: input
    id: teamname
    attributes:
      label: Team name (if "Other" selected)
  - type: input
    id: role
    attributes:
      label: Job Title
      placeholder: Senior Bioinformatician
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Role description
      description: Describe what you do and the projects/products/pipelines you work on
      placeholder: |
        Priyanka is a bioinformatician working on pipeline development and execution ...
    validations:
      required: true
  - type: input
    id: github
    attributes:
      label: GitHub
      placeholder: |
        https://github.com/priyanka-surana
    validations:
      required: true
  - type: input
    id: sanger
    attributes:
      label: Sanger Page
      placeholder: |
        https://www.sanger.ac.uk/person/surana-priyanka/
  - type: input
    id: twitter
    attributes:
      label: Twitter
      placeholder: |
        @psurana
  - type: input
    id: linkedin
    attributes:
      label: LinkedIn
      placeholder: |
        https://www.linkedin.com/in/priyanka-surana/
  - type: input
    id: mastodon
    attributes:
      label: Mastodon
      placeholder: |
        ...
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](http://pipelines.tol.sanger.ac.uk/code_of_conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
